version: '3'

services:

  ml:
    environment: 
      - PORT=8083
    build:
      context: ./ml
    image: ml-img
    ports:
      - "8084:8083"

  back:
    environment: 
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: ./back
    image: back-img
    ports:
      - "8082:8081"

  front:
    environment: 
      - PORT=8085
    build:
      context: ./front
    image: front-img
    ports:
      - "8086:8085"