version: '3'

services:

  ml:
    environment: 
      - PORT=8083
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=ibo_ml_db_user
      - PGPASSWORD=test-ibo_ml-psw
      - TRANSFORMERS_MODEL=ml_model
    build:
      context: ./ml
    image: ml-img
    ports:
      - "8084:8083"

  back:
    environment: 
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=docker
    build:
      context: ./back
    image: back-img
    ports:
      - "8082:8081"
      
  db:
    build: 
      context: ./db-dev
    image: db-img
    ports: 
      - "5432:5432"