
ibo:
  ml_service:
    url: http://ml:8083

  db:
    url: "jdbc:postgresql://db:5432/postgres?useSSL=false"
    user: "ibo_back_db_user"
    password: "test-ibo_back-psw"
    use_cloud_sql: false
    cloud_sql_instance: ~

