
ibo:
  ml_service:
    url: ${ML_SERVICE_URL}

  db:
    url: jdbc:mysql:///ibo_back # mysql url will be resolved by mysql-socket-factory-connector, we just set database schema
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    use_cloud_sql: true
    cloud_sql_instance: ${CLOUD_SQL_INSTANCE}


