/*
 * This file is generated by jOOQ.
 */
package co.globers.ibo.jooq.tables;


import co.globers.ibo.jooq.IboBack;
import co.globers.ibo.jooq.Keys;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EntityGuessing extends TableImpl<Record> {

    private static final long serialVersionUID = 1681744322;

    /**
     * The reference instance of <code>ibo_back.entity_guessing</code>
     */
    public static final EntityGuessing ENTITY_GUESSING = new EntityGuessing();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<Record> getRecordType() {
        return Record.class;
    }

    /**
     * The column <code>ibo_back.entity_guessing.id</code>.
     */
    public final TableField<Record, Integer> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('ibo_back.entity_guessing_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>ibo_back.entity_guessing.uri</code>.
     */
    public final TableField<Record, String> URI = createField(DSL.name("uri"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>ibo_back.entity_guessing.game_session_id</code>.
     */
    public final TableField<Record, Integer> GAME_SESSION_ID = createField(DSL.name("game_session_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ibo_back.entity_guessing.entity_to_guess_id</code>.
     */
    public final TableField<Record, Integer> ENTITY_TO_GUESS_ID = createField(DSL.name("entity_to_guess_id"), org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>ibo_back.entity_guessing.creation_datetime</code>.
     */
    public final TableField<Record, Timestamp> CREATION_DATETIME = createField(DSL.name("creation_datetime"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>ibo_back.entity_guessing</code> table reference
     */
    public EntityGuessing() {
        this(DSL.name("entity_guessing"), null);
    }

    /**
     * Create an aliased <code>ibo_back.entity_guessing</code> table reference
     */
    public EntityGuessing(String alias) {
        this(DSL.name(alias), ENTITY_GUESSING);
    }

    /**
     * Create an aliased <code>ibo_back.entity_guessing</code> table reference
     */
    public EntityGuessing(Name alias) {
        this(alias, ENTITY_GUESSING);
    }

    private EntityGuessing(Name alias, Table<Record> aliased) {
        this(alias, aliased, null);
    }

    private EntityGuessing(Name alias, Table<Record> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> EntityGuessing(Table<O> child, ForeignKey<O, Record> key) {
        super(child, key, ENTITY_GUESSING);
    }

    @Override
    public Schema getSchema() {
        return IboBack.IBO_BACK;
    }

    @Override
    public Identity<Record, Integer> getIdentity() {
        return Keys.IDENTITY_ENTITY_GUESSING;
    }

    @Override
    public UniqueKey<Record> getPrimaryKey() {
        return Keys.ENTITY_GUESSING_PKEY;
    }

    @Override
    public List<UniqueKey<Record>> getKeys() {
        return Arrays.<UniqueKey<Record>>asList(Keys.ENTITY_GUESSING_PKEY, Keys.ENTITY_GUESSING_URI_KEY);
    }

    @Override
    public List<ForeignKey<Record, ?>> getReferences() {
        return Arrays.<ForeignKey<Record, ?>>asList(Keys.ENTITY_GUESSING__ENTITY_GUESSING_GAME_SESSION_ID_FKEY, Keys.ENTITY_GUESSING__ENTITY_GUESSING_ENTITY_TO_GUESS_ID_FKEY);
    }

    public GameSession gameSession() {
        return new GameSession(this, Keys.ENTITY_GUESSING__ENTITY_GUESSING_GAME_SESSION_ID_FKEY);
    }

    public EntityToGuess entityToGuess() {
        return new EntityToGuess(this, Keys.ENTITY_GUESSING__ENTITY_GUESSING_ENTITY_TO_GUESS_ID_FKEY);
    }

    @Override
    public EntityGuessing as(String alias) {
        return new EntityGuessing(DSL.name(alias), this);
    }

    @Override
    public EntityGuessing as(Name alias) {
        return new EntityGuessing(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityGuessing rename(String name) {
        return new EntityGuessing(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EntityGuessing rename(Name name) {
        return new EntityGuessing(name, null);
    }
}
