/*
 * This file is generated by jOOQ.
 */
package co.globers.ibo.jooq;


import co.globers.ibo.jooq.tables.EntityGuessing;
import co.globers.ibo.jooq.tables.EntityGuessingSentence;
import co.globers.ibo.jooq.tables.EntityToGuess;
import co.globers.ibo.jooq.tables.GameSession;
import co.globers.ibo.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class IboBack extends SchemaImpl {

    private static final long serialVersionUID = -813577516;

    /**
     * The reference instance of <code>ibo_back</code>
     */
    public static final IboBack IBO_BACK = new IboBack();

    /**
     * The table <code>ibo_back.entity_guessing</code>.
     */
    public final EntityGuessing ENTITY_GUESSING = EntityGuessing.ENTITY_GUESSING;

    /**
     * The table <code>ibo_back.entity_guessing_sentence</code>.
     */
    public final EntityGuessingSentence ENTITY_GUESSING_SENTENCE = EntityGuessingSentence.ENTITY_GUESSING_SENTENCE;

    /**
     * The table <code>ibo_back.entity_to_guess</code>.
     */
    public final EntityToGuess ENTITY_TO_GUESS = EntityToGuess.ENTITY_TO_GUESS;

    /**
     * The table <code>ibo_back.game_session</code>.
     */
    public final GameSession GAME_SESSION = GameSession.GAME_SESSION;

    /**
     * The table <code>ibo_back.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private IboBack() {
        super("ibo_back", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ENTITY_GUESSING_ID_SEQ,
            Sequences.ENTITY_GUESSING_SENTENCE_ID_SEQ,
            Sequences.ENTITY_TO_GUESS_ID_SEQ,
            Sequences.GAME_SESSION_ID_SEQ,
            Sequences.USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            EntityGuessing.ENTITY_GUESSING,
            EntityGuessingSentence.ENTITY_GUESSING_SENTENCE,
            EntityToGuess.ENTITY_TO_GUESS,
            GameSession.GAME_SESSION,
            User.USER);
    }
}
