/*
 * This file is generated by jOOQ.
 */
package co.globers.ibo.jooq;


import co.globers.ibo.jooq.tables.EntityGuessing;
import co.globers.ibo.jooq.tables.EntityGuessingSentence;
import co.globers.ibo.jooq.tables.EntityToGuess;
import co.globers.ibo.jooq.tables.GameSession;
import co.globers.ibo.jooq.tables.User;

import javax.annotation.processing.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Record;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>ibo_back</code> schema.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<Record, Integer> IDENTITY_ENTITY_GUESSING = Identities0.IDENTITY_ENTITY_GUESSING;
    public static final Identity<Record, Integer> IDENTITY_ENTITY_GUESSING_SENTENCE = Identities0.IDENTITY_ENTITY_GUESSING_SENTENCE;
    public static final Identity<Record, Integer> IDENTITY_ENTITY_TO_GUESS = Identities0.IDENTITY_ENTITY_TO_GUESS;
    public static final Identity<Record, Integer> IDENTITY_GAME_SESSION = Identities0.IDENTITY_GAME_SESSION;
    public static final Identity<Record, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<Record> ENTITY_GUESSING_PKEY = UniqueKeys0.ENTITY_GUESSING_PKEY;
    public static final UniqueKey<Record> ENTITY_GUESSING_URI_KEY = UniqueKeys0.ENTITY_GUESSING_URI_KEY;
    public static final UniqueKey<Record> ENTITY_GUESSING_SENTENCE_PKEY = UniqueKeys0.ENTITY_GUESSING_SENTENCE_PKEY;
    public static final UniqueKey<Record> ENTITY_GUESSING_SENTENCE_URI_KEY = UniqueKeys0.ENTITY_GUESSING_SENTENCE_URI_KEY;
    public static final UniqueKey<Record> ENTITY_TO_GUESS_PKEY = UniqueKeys0.ENTITY_TO_GUESS_PKEY;
    public static final UniqueKey<Record> ENTITY_TO_GUESS_URI_KEY = UniqueKeys0.ENTITY_TO_GUESS_URI_KEY;
    public static final UniqueKey<Record> GAME_SESSION_PKEY = UniqueKeys0.GAME_SESSION_PKEY;
    public static final UniqueKey<Record> GAME_SESSION_URI_KEY = UniqueKeys0.GAME_SESSION_URI_KEY;
    public static final UniqueKey<Record> USER_PKEY = UniqueKeys0.USER_PKEY;
    public static final UniqueKey<Record> USER_URI_KEY = UniqueKeys0.USER_URI_KEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<Record, Record> ENTITY_GUESSING__ENTITY_GUESSING_GAME_SESSION_ID_FKEY = ForeignKeys0.ENTITY_GUESSING__ENTITY_GUESSING_GAME_SESSION_ID_FKEY;
    public static final ForeignKey<Record, Record> ENTITY_GUESSING__ENTITY_GUESSING_ENTITY_TO_GUESS_ID_FKEY = ForeignKeys0.ENTITY_GUESSING__ENTITY_GUESSING_ENTITY_TO_GUESS_ID_FKEY;
    public static final ForeignKey<Record, Record> ENTITY_GUESSING_SENTENCE__ENTITY_GUESSING_SENTENCE_ENTITY_GUESSING_ID_FKEY = ForeignKeys0.ENTITY_GUESSING_SENTENCE__ENTITY_GUESSING_SENTENCE_ENTITY_GUESSING_ID_FKEY;
    public static final ForeignKey<Record, Record> GAME_SESSION__GAME_SESSION_USER_ID_FKEY = ForeignKeys0.GAME_SESSION__GAME_SESSION_USER_ID_FKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<Record, Integer> IDENTITY_ENTITY_GUESSING = Internal.createIdentity(EntityGuessing.ENTITY_GUESSING, EntityGuessing.ENTITY_GUESSING.ID);
        public static Identity<Record, Integer> IDENTITY_ENTITY_GUESSING_SENTENCE = Internal.createIdentity(EntityGuessingSentence.ENTITY_GUESSING_SENTENCE, EntityGuessingSentence.ENTITY_GUESSING_SENTENCE.ID);
        public static Identity<Record, Integer> IDENTITY_ENTITY_TO_GUESS = Internal.createIdentity(EntityToGuess.ENTITY_TO_GUESS, EntityToGuess.ENTITY_TO_GUESS.ID);
        public static Identity<Record, Integer> IDENTITY_GAME_SESSION = Internal.createIdentity(GameSession.GAME_SESSION, GameSession.GAME_SESSION.ID);
        public static Identity<Record, Integer> IDENTITY_USER = Internal.createIdentity(User.USER, User.USER.ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<Record> ENTITY_GUESSING_PKEY = Internal.createUniqueKey(EntityGuessing.ENTITY_GUESSING, "entity_guessing_pkey", new TableField[] { EntityGuessing.ENTITY_GUESSING.ID }, true);
        public static final UniqueKey<Record> ENTITY_GUESSING_URI_KEY = Internal.createUniqueKey(EntityGuessing.ENTITY_GUESSING, "entity_guessing_uri_key", new TableField[] { EntityGuessing.ENTITY_GUESSING.URI }, true);
        public static final UniqueKey<Record> ENTITY_GUESSING_SENTENCE_PKEY = Internal.createUniqueKey(EntityGuessingSentence.ENTITY_GUESSING_SENTENCE, "entity_guessing_sentence_pkey", new TableField[] { EntityGuessingSentence.ENTITY_GUESSING_SENTENCE.ID }, true);
        public static final UniqueKey<Record> ENTITY_GUESSING_SENTENCE_URI_KEY = Internal.createUniqueKey(EntityGuessingSentence.ENTITY_GUESSING_SENTENCE, "entity_guessing_sentence_uri_key", new TableField[] { EntityGuessingSentence.ENTITY_GUESSING_SENTENCE.URI }, true);
        public static final UniqueKey<Record> ENTITY_TO_GUESS_PKEY = Internal.createUniqueKey(EntityToGuess.ENTITY_TO_GUESS, "entity_to_guess_pkey", new TableField[] { EntityToGuess.ENTITY_TO_GUESS.ID }, true);
        public static final UniqueKey<Record> ENTITY_TO_GUESS_URI_KEY = Internal.createUniqueKey(EntityToGuess.ENTITY_TO_GUESS, "entity_to_guess_uri_key", new TableField[] { EntityToGuess.ENTITY_TO_GUESS.URI }, true);
        public static final UniqueKey<Record> GAME_SESSION_PKEY = Internal.createUniqueKey(GameSession.GAME_SESSION, "game_session_pkey", new TableField[] { GameSession.GAME_SESSION.ID }, true);
        public static final UniqueKey<Record> GAME_SESSION_URI_KEY = Internal.createUniqueKey(GameSession.GAME_SESSION, "game_session_uri_key", new TableField[] { GameSession.GAME_SESSION.URI }, true);
        public static final UniqueKey<Record> USER_PKEY = Internal.createUniqueKey(User.USER, "user_pkey", new TableField[] { User.USER.ID }, true);
        public static final UniqueKey<Record> USER_URI_KEY = Internal.createUniqueKey(User.USER, "user_uri_key", new TableField[] { User.USER.URI }, true);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<Record, Record> ENTITY_GUESSING__ENTITY_GUESSING_GAME_SESSION_ID_FKEY = Internal.createForeignKey(Keys.GAME_SESSION_PKEY, EntityGuessing.ENTITY_GUESSING, "entity_guessing_game_session_id_fkey", new TableField[] { EntityGuessing.ENTITY_GUESSING.GAME_SESSION_ID }, true);
        public static final ForeignKey<Record, Record> ENTITY_GUESSING__ENTITY_GUESSING_ENTITY_TO_GUESS_ID_FKEY = Internal.createForeignKey(Keys.ENTITY_TO_GUESS_PKEY, EntityGuessing.ENTITY_GUESSING, "entity_guessing_entity_to_guess_id_fkey", new TableField[] { EntityGuessing.ENTITY_GUESSING.ENTITY_TO_GUESS_ID }, true);
        public static final ForeignKey<Record, Record> ENTITY_GUESSING_SENTENCE__ENTITY_GUESSING_SENTENCE_ENTITY_GUESSING_ID_FKEY = Internal.createForeignKey(Keys.ENTITY_GUESSING_PKEY, EntityGuessingSentence.ENTITY_GUESSING_SENTENCE, "entity_guessing_sentence_entity_guessing_id_fkey", new TableField[] { EntityGuessingSentence.ENTITY_GUESSING_SENTENCE.ENTITY_GUESSING_ID }, true);
        public static final ForeignKey<Record, Record> GAME_SESSION__GAME_SESSION_USER_ID_FKEY = Internal.createForeignKey(Keys.USER_PKEY, GameSession.GAME_SESSION, "game_session_user_id_fkey", new TableField[] { GameSession.GAME_SESSION.USER_ID }, true);
    }
}
