/*
 * This file is generated by jOOQ.
 */
package co.globers.ibo.jooq;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.Internal;


/**
 * Convenience access to all sequences in ibo_back
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>ibo_back.entity_guessing_id_seq</code>
     */
    public static final Sequence<Integer> ENTITY_GUESSING_ID_SEQ = Internal.createSequence("entity_guessing_id_seq", IboBack.IBO_BACK, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>ibo_back.entity_guessing_sentence_id_seq</code>
     */
    public static final Sequence<Integer> ENTITY_GUESSING_SENTENCE_ID_SEQ = Internal.createSequence("entity_guessing_sentence_id_seq", IboBack.IBO_BACK, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>ibo_back.entity_to_guess_id_seq</code>
     */
    public static final Sequence<Integer> ENTITY_TO_GUESS_ID_SEQ = Internal.createSequence("entity_to_guess_id_seq", IboBack.IBO_BACK, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>ibo_back.game_session_id_seq</code>
     */
    public static final Sequence<Integer> GAME_SESSION_ID_SEQ = Internal.createSequence("game_session_id_seq", IboBack.IBO_BACK, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);

    /**
     * The sequence <code>ibo_back.user_id_seq</code>
     */
    public static final Sequence<Integer> USER_ID_SEQ = Internal.createSequence("user_id_seq", IboBack.IBO_BACK, org.jooq.impl.SQLDataType.INTEGER.nullable(false), null, null, null, null, false, null);
}
