/*
 * This file is generated by jOOQ.
 */
package co.globers.ibo.jooq;


import co.globers.ibo.jooq.tables.EntityGuessing;
import co.globers.ibo.jooq.tables.EntityGuessingSentence;
import co.globers.ibo.jooq.tables.EntityToGuess;
import co.globers.ibo.jooq.tables.GameSession;
import co.globers.ibo.jooq.tables.User;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in ibo_back
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ibo_back.entity_guessing</code>.
     */
    public static final EntityGuessing ENTITY_GUESSING = EntityGuessing.ENTITY_GUESSING;

    /**
     * The table <code>ibo_back.entity_guessing_sentence</code>.
     */
    public static final EntityGuessingSentence ENTITY_GUESSING_SENTENCE = EntityGuessingSentence.ENTITY_GUESSING_SENTENCE;

    /**
     * The table <code>ibo_back.entity_to_guess</code>.
     */
    public static final EntityToGuess ENTITY_TO_GUESS = EntityToGuess.ENTITY_TO_GUESS;

    /**
     * The table <code>ibo_back.game_session</code>.
     */
    public static final GameSession GAME_SESSION = GameSession.GAME_SESSION;

    /**
     * The table <code>ibo_back.user</code>.
     */
    public static final User USER = User.USER;
}
